### ISSUE TITLE
Release pacmod3 into ROS Noetic

### ISSUE THREAD

**Issue by wep21** [astuff/pacmod3#69]
Do you have any plan to release pacmod3 into ROS Noetic?

**Comment by dvangeyn-as** [comment]
@wep21: Apologies for not writing back sooner. We do have plans to release many of our ROS drivers as Noetic packages, however, this work has not yet been scheduled to happen, as we plan to both release and validate.

**Comment by icolwell-as** [comment]
@wep21, a ROS Noetic version of this driver will be released by the end of November.

**Comment by icolwell-as** [comment]
@wep21, Version 2.0.0 has been released on Noetic, see the README for installation instructions.
